import { Review } from './types';

// ═══════════════════════════════════════════════════════════════
// All reviews, sorted best-first (most detailed / impactful at top,
// vague one-liners at bottom). Prices & time-since-posted redacted.
// ═══════════════════════════════════════════════════════════════

export const ALL_REVIEWS: Review[] = [
    // ───────── TOP-TIER — detailed, emotional, highly descriptive ─────────
    {
        name: 'Jasmine Y.',
        text: "Hire them!!! LOVE THEIR WORK! I hired them to re-create a modern look that I could not find factory made to add to my townhouse. Other companies took forever getting back to me. When I called initially Juan answered, I sent him the measurements in a sketch and a photo of what I wanted, sent me a quote same day, the timeline was exactly as promised. I had concerns about the fence because in the photo I requested it didn't look quite right... but when I asked to go see it in person it was PERFECT!!! The price was 100% fair and I ABSOLUTELY love their work. They aren't smooth talkers and hagglers which I like. Straight to the point. Honest Texas family owned business. I will be hiring them for any future steel/fence jobs and recommending them to everyone!!! I have gotten so many compliments from my neighbors! The fence is SOLID!",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['custom design', 'fair pricing', 'family business', 'honest'],
    },
    {
        name: 'Anna F.',
        text: "My entire experience with this company was top tier. I had called several companies for estimates on having a new gate installed for the driveway of a house I just bought. Juan responded right away, met me at the house, and sent over the estimate faster than expected. Communication was great. When it was time for the installation, everything went smoothly. He assisted with getting me connected to the miQ, and when we realized I needed some additional equipment, he went to Best Buy and got it. He made two trips there but managed to get my modem to connect! He definitely went above and beyond what most other companies would do! Additionally, he came back a couple days later and replaced the caps for me on a small piece of older wrought iron fencing. I'm picky about things like this but, after exceeding my expectations, I would definitely recommend him!",
        source: 'Yelp',
        stars: 5,
        project: 'Driveway Gate Installation',
        category: 'gates',
        themes: ['above and beyond', 'fast response', 'great communication'],
    },
    {
        name: 'Cheri N.',
        text: "I highly recommend JN Ornamental Design. There are not enough words to express the service and highest level of quality and trust that I received from the JN Ornamental Design business. Juan and his team gave me unparalleled beauty and excellence for the work they performed. Thank you for a most memorable and outstanding customer experience!",
        source: 'Google',
        stars: 5,
        category: 'general',
        themes: ['quality', 'trust', 'outstanding experience'],
    },
    {
        name: 'Renee G.',
        text: "Juan did an exceptional job with the two gates I replaced. The design was exactly what I wanted and the wrought iron is substantial. He does quality work and he did both gates for half the amount of the two quotes I received from others. He oversees the work and did the job in exact time frame he quoted. I am thrilled and the neighbors love my new gates too!! I've already recommended him for another job.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Gate Replacement',
        category: 'gates',
        themes: ['exceptional', 'custom design', 'competitive pricing'],
    },
    {
        name: 'Everett C.',
        text: "EXCELLENT WORK! Very professional from the initial contact through final clean-up. Highly skilled and meticulous about measurement, post setting, welding, and painting. Their quote was literally half the other two. Their attitude and work ethic was Outstanding. Highly recommend.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['excellent work', 'professional', 'competitive pricing'],
    },
    {
        name: 'David V.',
        text: "Very very pleased with JN Ornamental Design, this family owned business is professional and they do exceptional design work. They were honest, showed up when they said they would, knowledgeable and experienced. Upon completion of the job they explained how the auto open gate worked, cleaned the work-site and made sure we were satisfied. They truly deserve this 5 star rating.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['exceptional design', 'honest', 'family business'],
    },
    {
        name: 'Michael D.',
        text: "The process of working with JN Ornamental Design was Outstanding! Juan is a very knowledgeable owner, and explained everything in detail of the work we needed to have completed. Their fence crew was on time, clean, and did an Amazing Job on our fence. Highly recommended them if you need custom welding and painting on a metal fence!!! Thanks again, and we will definitely use your services again in the future.",
        source: 'Google',
        stars: 5,
        project: 'Custom Metal Fence',
        category: 'fences',
        themes: ['outstanding', 'knowledgeable', 'custom welding'],
    },
    {
        name: 'Samia B.',
        text: "Juan is not just professional but talented at designing and his gates are more than phenomenal. My dad continues to use him. He has built and designed 4 gates for us in total. I hope he expands to other services because he is also responsive and honest.",
        source: 'Google',
        stars: 5,
        project: 'Custom Gate Design',
        category: 'gates',
        themes: ['talented designer', 'repeat customer', 'responsive'],
    },
    {
        name: 'Marsha I.',
        text: "One of the most satisfying contractor experiences I've ever had. Juan and his family were professional, precise, on time and efficient and delivered exactly what they promised. I have nothing but great things to say about JN Ornamental Design and I would highly recommend them for any iron or wood gate/fence work.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['satisfying experience', 'precise', 'on time'],
    },
    {
        name: 'H R.',
        text: "We had a great experience with Juan at JN, from start to finish. We wish everyone ran their business this well! Juan was fast, helpful, thorough, and courteous through out the process of tearing out an old patio gate and installing a beautiful new wrought iron gate. His crew arrived on time, and were neat in every way. Our patio and landscaping were left clean and practically looked untouched. We got a new gate installed quickly! We will definitely use JN again & would recommend them.",
        source: 'Yelp',
        stars: 5,
        project: 'Wrought Iron Gate Installation',
        category: 'gates',
        themes: ['great experience', 'thorough', 'clean crew'],
    },
    {
        name: 'Yana R.',
        text: "Juan and his father did a great job replacing the metal balcony railing. Easy to work with and very good customer service. They worked with us to get the design right and provided valuable recommendations. Always reachable via email/phone/sms. As a result, we are going to use this company for our next project. I would highly recommend this company!",
        source: 'Thumbtack',
        stars: 5,
        project: 'Balcony Railing Replacement',
        category: 'railings',
        themes: ['great job', 'easy to work with', 'design collaboration'],
    },
    {
        name: 'Brooks C.',
        text: "This is truly a family operation with mother, father and son all contributing to the final product. The fabrication and installation of our spiral staircase exceeded all expectations and is now a great addition to our home.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Spiral Staircase Installation',
        category: 'railings',
        themes: ['family operation', 'exceeded expectations', 'spiral staircase'],
    },
    {
        name: 'Kim W.',
        text: "Juan and his Father did an excellent job installing my metal rails. They ran into an issue because my purchased parts didn't quite work. Instead of telling me that they couldn't do anything, they worked on it until they found a solution that worked perfectly. I would definitely use their services again and would recommend this team to anyone needing iron work. My staircase looks amazing!",
        source: 'Thumbtack',
        stars: 5,
        project: 'Metal Railing Installation',
        category: 'railings',
        themes: ['problem solving', 'excellent job', 'perseverance'],
    },
    {
        name: 'Cintia L.',
        text: "I am very much happy and satisfied of the amazing job that Juan and his crew did. I'm in love with my fence. It's really beautiful and it's really beneficial for my dog. I would highly recommend JN Ornamental Design to anyone that needs a fence. Thank you so much to Juan for taking his valuable time to help me out with this project.",
        source: 'Yelp',
        stars: 5,
        project: 'Fence Installation',
        category: 'fences',
        themes: ['amazing job', 'beautiful', 'highly recommend'],
    },
    {
        name: 'JoAnna A.',
        text: "EXCEPTIONAL. GREAT job; GREAT service; GREAT price. Professional family business. After installation, we decided a few days later to have them install a hydraulic device to keep the gate closed, and they were on it THE SAME DAY! Highly, HIGHLY recommend.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['exceptional', 'responsive', 'family business'],
    },
    {
        name: 'Patrick L.',
        text: "JN's price was very competitive, and the finished product was even better than I hoped. Juan is easy to work with, knowledgeable, informative, and his pride in his work shows. Highly recommended!",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['competitive price', 'knowledgeable', 'pride in work'],
    },
    {
        name: 'Tracy N.',
        text: "Came on a Saturday morning after I called to fix a wrought iron gate that was off track, stuck and would not open. Very friendly and personable service, also affordable. Wouldn't have been able to open the gate without them. Also recommended a permanent solution to fix it. Thank you so much!!! Highly recommend their service 5++ Stars.",
        source: 'Yelp',
        stars: 5,
        project: 'Wrought Iron Gate Repair',
        category: 'gates',
        themes: ['fast response', 'friendly', 'affordable'],
    },
    {
        name: 'Denver G.',
        text: "I had many people come look at my gate and it would work fine for a few days before it would mess up again. Everyone told me I needed to do a big giant repair in order to have everything working correctly. Juan however replaced one part and it's been working correctly. He didn't try to up-sell me or charge me a bunch for unnecessary repairs. Definitely recommend.",
        source: 'Yelp',
        stars: 5,
        project: 'Gate Repair',
        category: 'access-control',
        themes: ['honest', 'no upselling', 'effective repair'],
    },
    {
        name: 'Maria G.',
        text: "Excellent service from Juan! I needed someone right away to handle an emergency issue with my non-working gate, and Juan was kind enough to fit me in. He was honest, straightforward, and quick to identify the problem. It's rare to find such reliable and transparent service. Juan is absolutely someone I'd recommend!!",
        source: 'Yelp',
        stars: 5,
        project: 'Gate Repair',
        category: 'access-control',
        themes: ['emergency service', 'honest', 'reliable'],
    },
    {
        name: 'Linh N.',
        text: "Fast response, professional service, fair price. Same day visit and quote. Juan checked in at each step. My fence weld project was done quickly. Highly recommend. Thanks Juan!",
        source: 'Yelp',
        stars: 5,
        project: 'Fence Welding',
        category: 'fences',
        themes: ['fast response', 'professional', 'fair price'],
    },
    {
        name: 'Naoko T.',
        text: "Fences were installed beautifully and perfectly. They were very punctual and worked hard. We also asked to install a spiral staircase. It was also nicely done. We were satisfied with their work 100%. They were trustworthy in their work.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Fence & Spiral Staircase Installation',
        category: 'fences',
        themes: ['beautiful installation', 'punctual', 'trustworthy'],
    },
    {
        name: 'Barbara D.',
        text: "These people are totally dependable... an important attribute to me. They showed up when they said they would, designed a beautiful gate and delivered and installed the gate the day they promised. I'd use them again in a heartbeat. No hesitation here.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Custom Gate Design & Installation',
        category: 'gates',
        themes: ['dependable', 'beautiful gate', 'on time'],
    },
    {
        name: 'Derek H.',
        text: "Excellent craftsmanship! Prompt work! I am very happy with my railings and gates!",
        source: 'Thumbtack',
        stars: 5,
        project: 'Railings & Gates Installation',
        category: 'railings',
        themes: ['excellent craftsmanship', 'prompt'],
    },
    {
        name: 'Margaret K.',
        text: "Outstanding job. Juan was professional, efficient and obviously focused on our satisfaction. The team worked well and cleaned up as they worked. Very pleased with the finished job. Don't think twice about hiring this young man, he knows his stuff!!!",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['outstanding', 'professional', 'efficient'],
    },
    {
        name: 'Chelsea D.',
        text: "They have done work at my property and they are so professional and the work is good! I will continue to use them for my property! Juan thank you so much!",
        source: 'Google',
        stars: 5,
        category: 'general',
        themes: ['professional', 'repeat customer'],
    },
    // ───────── MID-TIER — solid reviews with some detail ─────────
    {
        name: 'Emily R.',
        text: "Juan did awesome on our fence. The quality is amazing and the price was fair. Our home and life is much improved thanks to his work!",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['amazing quality', 'fair price'],
    },
    {
        name: 'Monique M.',
        text: "This father and son team are very professional and completely explained the work before they started. They completed the job when they said they would. I'm extremely pleased with the work.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['professional', 'on schedule'],
    },
    {
        name: 'Betsy S.',
        text: "Juan did an excellent job. He was prompt on getting with me. He explained everything that he would be doing, and followed through. I would recommend Juan to any of my friends.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['excellent job', 'prompt', 'follows through'],
    },
    {
        name: 'George E.',
        text: "J.N Ornamental Design, LLC did a great job installing my new chain link fence. They were very professional, courteous, and always on time.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Chain Link Fence Installation',
        category: 'fences',
        themes: ['great job', 'professional', 'on time'],
    },
    {
        name: 'A.C.',
        text: "Project was completed 3 days ahead of completion time. Very responsive and respectful.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['ahead of schedule', 'responsive'],
    },
    {
        name: 'Shareena B.',
        text: "We didn't have a large budget for what we needed done, however they were very understanding and worked with us and we were able to get the job done. If we need this done again in the future, they would definitely be the first ones we call.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Commercial Wrought Iron Fence',
        category: 'fences',
        themes: ['understanding', 'budget-friendly'],
    },
    {
        name: 'Kathleen B.',
        text: "I was having trouble with 2 small iron gates. They analyzed both problems and performed the work needed. The fence and gates have never looked better.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Iron Gate Repair',
        category: 'gates',
        themes: ['problem solving', 'quality work'],
    },
    {
        name: 'John S.',
        text: "All the employees who installed my fence were very professional, courteous and easy to converse with. They did an outstanding job. I highly recommend them.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['professional', 'courteous', 'outstanding'],
    },
    {
        name: 'Mamie E.',
        text: "This young owner is motivated to satisfy his customer. My fence was built quickly and to my satisfaction. My neighbors like it too!!",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['motivated', 'fast', 'satisfied'],
    },
    {
        name: 'Paula G.',
        text: "This family owned business was very good. They were very accommodating and helped with design. Juan and his father were punctual and did their work efficiently. I would definitely hire again.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Metal Railing Installation',
        category: 'railings',
        themes: ['family business', 'accommodating', 'punctual'],
    },
    {
        name: 'Corey S.',
        text: "Juan gave me an estimate based on the photos and project description. He was able to come out quickly. He and his crew did good work, were respectful of property, and cleaned up when they were done. I would use this company again, and would consider them for larger projects.",
        source: 'Yelp',
        stars: 5,
        project: 'Pedestrian Gate Repair',
        category: 'gates',
        themes: ['good work', 'respectful', 'clean'],
    },
    {
        name: 'David C.',
        text: "Juan and Nickolas were very quick to respond to our request for a quote, and very fast once selected to get to work. Finished in less than a day and were just great to work with! I will be recommending JN Ornamental Fencing in my Neighborhood Referral!",
        source: 'Thumbtack',
        stars: 5,
        project: 'Chain Link Fence Installation',
        category: 'fences',
        themes: ['fast response', 'quick work', 'great to work with'],
    },
    {
        name: 'Chrystine W.',
        text: "Fantastic quality, great customer service. Worth every penny to protect our girls from falling out of the opening overlooking our living room. Perfect!!",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['fantastic quality', 'great service', 'safety'],
    },
    {
        name: 'Kevin M.',
        text: "Family run business. Very polite and very good quality work. Also, price was far more reasonable than the other two bids that we got.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['family business', 'quality', 'reasonable price'],
    },
    {
        name: 'Nancy V.',
        text: "Professional and great quality of work. Project was completed in very reasonable time frame.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['professional', 'quality'],
    },
    {
        name: 'Linda H.',
        text: "Very professional. Did the work in a timely manner. I will use them again as needed. Thank you so much.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Chain Link Fence Installation',
        category: 'fences',
        themes: ['professional', 'timely'],
    },
    {
        name: 'Imran T.',
        text: "Juan does excellent work and we highly recommend him. Mom and Dad a part of the team.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['excellent work', 'family team'],
    },
    {
        name: 'Kevin K.',
        text: "They were great. Came and did a quote and the job in the same week!! Very prompt and the fence looks amazing. Will use them again for other projects.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['prompt', 'amazing fence'],
    },
    {
        name: 'Teresa W.',
        text: "Very responsive, competitive rates, and professional. I would recommend their services.",
        source: 'Yelp',
        stars: 5,
        category: 'general',
        themes: ['responsive', 'competitive', 'professional'],
    },
    // ───────── LOWER-TIER — short but positive ─────────
    {
        name: 'Vincent F.',
        text: "They do a good job and are great value for the money. I will maybe use them again for some additional iron work at one of my other properties.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['good job', 'great value'],
    },
    {
        name: 'Wadah A.',
        text: "On time, reasonable price, good quality.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['on time', 'reasonable price', 'quality'],
    },
    {
        name: 'George F.',
        text: "Nice family run business. They were timely in doing the work.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['family business', 'timely'],
    },
    {
        name: 'CHARLOTTE W.',
        text: "JN Ornamental Design was excellent, we couldn't be happier!",
        source: 'Thumbtack',
        stars: 5,
        category: 'general',
        themes: ['excellent'],
    },
    {
        name: 'Gilbert C.',
        text: "Very kind and did a professional job. I would recommend JN to anyone.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Steel Fence Installation',
        category: 'fences',
        themes: ['kind', 'professional'],
    },
    {
        name: 'Joshua A.',
        text: "Great work! Great service! Juan is a Man of his word! These 3 things make him my iron work go-to man! Thx JN Ornamental Design.",
        source: 'Google',
        stars: 5,
        category: 'general',
        themes: ['great work', 'reliable'],
    },
    {
        name: 'Chuck G.',
        text: "Excellent!",
        source: 'Thumbtack',
        stars: 5,
        project: 'Metal Stairs & Railings',
        category: 'railings',
        themes: ['excellent'],
    },
    {
        name: 'Yvonne J.',
        text: "Juan was pleasant to work with.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['pleasant'],
    },
    {
        name: 'Judy P.',
        text: "A family operated business that is reliable.",
        source: 'Thumbtack',
        stars: 4,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['family business', 'reliable'],
    },
    {
        name: 'Joshua A.',
        text: "Good work. Professional service.",
        source: 'Thumbtack',
        stars: 4,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['good work', 'professional'],
    },
    {
        name: 'Marco P.',
        text: "I would use them again in the future.",
        source: 'Thumbtack',
        stars: 5,
        project: 'Wrought Iron Fence Installation',
        category: 'fences',
        themes: ['satisfied'],
    },
];

// ═══════════════════════════════════════════════════════════════
// Filtered arrays by category
// ═══════════════════════════════════════════════════════════════

export const FENCE_REVIEWS = ALL_REVIEWS.filter(
    (r) => r.category === 'fences'
);

export const GATE_REVIEWS = ALL_REVIEWS.filter(
    (r) => r.category === 'gates'
);

export const RAILING_REVIEWS = ALL_REVIEWS.filter(
    (r) => r.category === 'railings'
);

export const ACCESS_CONTROL_REVIEWS = ALL_REVIEWS.filter(
    (r) => r.category === 'access-control' || r.category === 'gates'
);

/** Top reviews for the homepage static cards (first 6, best-of-the-best). */
export const HOME_REVIEWS = ALL_REVIEWS.slice(0, 6);
